import type { Metadata } from "next";
import { ToastContainer } from 'react-toastify';
import { Lexend, Geist_Mono, Playwrite_GB_S } from "next/font/google";
import 'react-toastify/dist/ReactToastify.css';
import { ThemeProvider } from 'next-themes'
import "./globals.css";

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playwriteGb = Playwrite_GB_S({
  weight: "400",
  variable: "--font-playwrite-gb",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${lexend.variable} ${geistMono.variable} ${playwriteGb.variable}`}>
        <ThemeProvider attribute="data-theme">
          {children}
          <ToastContainer
            position="bottom-center"
            autoClose={1000}
            limit={1}
            hideProgressBar
            newestOnTop
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            theme="dark"
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
